import Foundation

//Problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//Answer:  4613732

func fibonacci(_ n: Int) -> Int {
  var a = 0
  var b = 1
  
  for _ in 0..<n {
    let temp = a
    a = b
    b = temp + b
  }
  return a
}

var sum: Int = 0

for i in 0... {
  if sum <= 4_000_000 {
    let number: Int = fibonacci(i)
    if number.isMultiple(of: 2) {
      sum += number
    }
  } else {
    break
  }
}

sum
